<?php
/**
* @file
* PPS Energy Tracker, provides the end user with a means to see historical and predictive electricity pricing.
* This file in particular routes the various pages to the correct TWIG templates.
*/

use Drupal\Core\Routing\RouteMatchInterface;

/**
* Implements hook_theme()
*/
function pps_energy_tracker_theme($existing, $type, $theme, $path) {
  return array(
    'pps_energy_tracker' => array(
      'variables' => array(),
      'template' => 'pps_energy_tracker',
    ),
    'pps_energy_tracker_account_management' => array(
      'variables' => array(
        'element_content' => NULL,
      ),
      'template' => 'pps_energy_tracker_account_management',
    ),
    'pps_energy_tracker_electricity_graphs' => array(
      'variables' => array(
        'graph_data' => NULL,
      ),
      'template' => 'pps_energy_tracker_electricity_graphs',
    ),
    'pps_energy_tracker_natural_gas_graphs' => array(
      'variables' => array(),
      'template' => 'pps_energy_tracker_natural_gas_graphs',
    ),
    'pps_energy_tracker_generic_graphs' => array(
      'variables' => array(
        'element_content' => NULL,
        'graph_data' => NULL,
      ),
    'template' => 'pps_energy_tracker_generic_graphs',
    ),
  );
}