<?php
/**
 * Created by PhpStorm.
 * User: alexm
 * Date: 5/25/2016
 * Time: 1:18 PM
 *
 * Default implementation of the account management form. Usable for Add/Update
 * Additional implementation will potentially be needed for Deletion
 * To implement this form we need to assign it into a block and then reference it on a template.
 *
 */

namespace Drupal\pps_energy_tracker\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

//TODO: Remove if we aren't redirecting or having any AJAX calls
/**
use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Url;
**/

class Account_Management_Form extends ConfigFormBase {

    /**
     * @return string
     *
     * Returns the Form ID for Drupal to call the correct form.
     */
    public function getFormId(){
        return 'Account_Management_Form';
    }

    /**
     * @param array $form
     * @param FormStateInterface $form_state
     * @return array
     *
     * Provides the generation of the form needed to modify Account Based data.
     */
    public function buildForm(array $form, FormStateInterface $form_state){
        $form = parent::buildForm($form, $form_state);

        $form['test'] = array(
            '#type' => 'select',
            '#title' => 'Test Form Element',
            '#options' => ['Foo1', 'Foo2', 'Foo3'],
        );

        return $form;
    }

    /**
     * @param array $form
     * @param FormStateInterface $form_state
     *
     * Provides basic validation of the inputted account data.
     */
    public function validateForm(array &$form, FormStateInterface $form_state) {
        parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $form
     * @param FormStateInterface $form_state
     *
     * Submit the form for a redirect and Database storage
     */
    public function submitForm(array &$form, FormStateInterface $form_state) {
        parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
    }

    /**
     * Drupal required function alternative is define class as Abstract
     */
    //TODO: What does this do?
    public function getEditableConfigNames() {
        // TODO: Implement getEditableConfigNames() method.
        return [
            'pps_energy_tracker.settings',
        ];
    }


}
